name: 🎭 Tests
on:
  push:
    paths-ignore:
      - .chglog/**
      - .github/**
      - '!.github/workflows/tests.yml'
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .htaccess
      - '**.md'
    branches:
      - develop
      - master
  pull_request:
    paths-ignore:
      - .chglog/**
      - .github/**
      - '!.github/workflows/tests.yml'
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .htaccess
      - '**.md'
    branches:
      - develop
      - master
jobs:
  silverstripe-module:
    name: 🧰 Silverstripe Module Testsuite
    uses: syntro-opensource/workflows/.github/workflows/silverstripe-module.yml@4
    with:
      phpunit: true
      # phpunit_config_file:
      phpstan: true
      # phpstan_config:
      # phpstan_bootstrap:
      phpcs: true